<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <RoslynVersion>5.0.0</RoslynVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == '$(CurrentTargetFramework)' Or '$(MSBuildProjectName)' == 'CommentSense.PerformanceTests'">
    <RoslynVersion>5.9.0</RoslynVersion>
  </PropertyGroup>
  <ItemGroup>
    <!-- Source -->
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="5.9.0-1.26328.17"/>
    <PackageVersion Include="Microsoft.CodeAnalysis.Common" Version="$(RoslynVersion)"/>
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="$(RoslynVersion)"/>
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="$(RoslynVersion)"/>
    <PackageVersion Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="$(RoslynVersion)"/>

    <!-- Test -->
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1"/>
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing" Version="1.1.4"/>
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.CodeFix.Testing" Version="1.1.4"/>
    <PackageVersion Include="NUnit" Version="5.0.0"/>
    <PackageVersion Include="NUnit.Analyzers" Version="4.15.0"/>
    <PackageVersion Include="NUnit3TestAdapter" Version="6.3.0"/>
    <PackageVersion Include="Moq" Version="4.21.0"/>
    <PackageVersion Include="coverlet.MTP" Version="10.1.0"/>
    <PackageVersion Include="System.Formats.Asn1" Version="10.0.2"/>

    <!-- Build -->
    <PackageVersion Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="$(RoslynVersion)" />
    <PackageVersion Include="MinVer" Version="8.0.0" />
    <PackageVersion Include="BenchmarkDotNet" Version="0.16.0-preview.2" />
    <PackageVersion Include="BenchmarkDotNet.Diagnostics.Windows" Version="0.16.0-preview.2" />
    <PackageVersion Include="Microsoft.CodeAnalysis.ResxSourceGenerator" Version="5.0.0-1.25277.114" />
  </ItemGroup>
</Project>
