<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
    <ImplicitUsings>disable</ImplicitUsings>
    <StartupObject>CommentSense.PerformanceTests.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="BenchmarkDotNet.Diagnostics.Windows" Condition="'$(OS)' == 'Windows_NT'" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CommentSense.Analyzers\CommentSense.Analyzers.csproj" />
    <ProjectReference Include="..\CommentSense.TestHelpers\CommentSense.TestHelpers.csproj" />
  </ItemGroup>

</Project>
