<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.Common" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="CommentSense.Analyzers"/>
        <InternalsVisibleTo Include="CommentSense.CodeFixes"/>
    </ItemGroup>

</Project>
