<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Moq" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\CommentSense.Core\CommentSense.Core.csproj"/>
        <ProjectReference Include="..\CommentSense.TestHelpers\CommentSense.TestHelpers.csproj"/>
    </ItemGroup>

</Project>
