//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommentSense.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommentSense.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissingDocumentationTitle.
        /// </summary>
        internal static string MissingDocumentationTitle {
            get {
                return ResourceManager.GetString("MissingDocumentationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissingDocumentationMessage.
        /// </summary>
        internal static string MissingDocumentationMessage {
            get {
                return ResourceManager.GetString("MissingDocumentationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissingDocumentationDescription.
        /// </summary>
        internal static string MissingDocumentationDescription {
            get {
                return ResourceManager.GetString("MissingDocumentationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissingParameterDocumentationTitle.
        /// </summary>
        internal static string MissingParameterDocumentationTitle {
            get {
                return ResourceManager.GetString("MissingParameterDocumentationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissingParameterDocumentationMessage.
        /// </summary>
        internal static string MissingParameterDocumentationMessage {
            get {
                return ResourceManager.GetString("MissingParameterDocumentationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissingParameterDocumentationDescription.
        /// </summary>
        internal static string MissingParameterDocumentationDescription {
            get {
                return ResourceManager.GetString("MissingParameterDocumentationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StrayParameterDocumentationTitle.
        /// </summary>
        internal static string StrayParameterDocumentationTitle {
            get {
                return ResourceManager.GetString("StrayParameterDocumentationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StrayParameterDocumentationMessage.
        /// </summary>
        internal static string StrayParameterDocumentationMessage {
            get {
                return ResourceManager.GetString("StrayParameterDocumentationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StrayParameterDocumentationDescription.
        /// </summary>
        internal static string StrayParameterDocumentationDescription {
            get {
                return ResourceManager.GetString("StrayParameterDocumentationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissingTypeParameterDocumentationTitle.
        /// </summary>
        internal static string MissingTypeParameterDocumentationTitle {
            get {
                return ResourceManager.GetString("MissingTypeParameterDocumentationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissingTypeParameterDocumentationMessage.
        /// </summary>
        internal static string MissingTypeParameterDocumentationMessage {
            get {
                return ResourceManager.GetString("MissingTypeParameterDocumentationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissingTypeParameterDocumentationDescription.
        /// </summary>
        internal static string MissingTypeParameterDocumentationDescription {
            get {
                return ResourceManager.GetString("MissingTypeParameterDocumentationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StrayTypeParameterDocumentationTitle.
        /// </summary>
        internal static string StrayTypeParameterDocumentationTitle {
            get {
                return ResourceManager.GetString("StrayTypeParameterDocumentationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StrayTypeParameterDocumentationMessage.
        /// </summary>
        internal static string StrayTypeParameterDocumentationMessage {
            get {
                return ResourceManager.GetString("StrayTypeParameterDocumentationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StrayTypeParameterDocumentationDescription.
        /// </summary>
        internal static string StrayTypeParameterDocumentationDescription {
            get {
                return ResourceManager.GetString("StrayTypeParameterDocumentationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissingReturnValueDocumentationTitle.
        /// </summary>
        internal static string MissingReturnValueDocumentationTitle {
            get {
                return ResourceManager.GetString("MissingReturnValueDocumentationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissingReturnValueDocumentationMessage.
        /// </summary>
        internal static string MissingReturnValueDocumentationMessage {
            get {
                return ResourceManager.GetString("MissingReturnValueDocumentationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissingReturnValueDocumentationDescription.
        /// </summary>
        internal static string MissingReturnValueDocumentationDescription {
            get {
                return ResourceManager.GetString("MissingReturnValueDocumentationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnresolvedCrefTitle.
        /// </summary>
        internal static string UnresolvedCrefTitle {
            get {
                return ResourceManager.GetString("UnresolvedCrefTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnresolvedCrefMessage.
        /// </summary>
        internal static string UnresolvedCrefMessage {
            get {
                return ResourceManager.GetString("UnresolvedCrefMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnresolvedCrefDescription.
        /// </summary>
        internal static string UnresolvedCrefDescription {
            get {
                return ResourceManager.GetString("UnresolvedCrefDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParameterOrderMismatchTitle.
        /// </summary>
        internal static string ParameterOrderMismatchTitle {
            get {
                return ResourceManager.GetString("ParameterOrderMismatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParameterOrderMismatchMessage.
        /// </summary>
        internal static string ParameterOrderMismatchMessage {
            get {
                return ResourceManager.GetString("ParameterOrderMismatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParameterOrderMismatchDescription.
        /// </summary>
        internal static string ParameterOrderMismatchDescription {
            get {
                return ResourceManager.GetString("ParameterOrderMismatchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateParameterDocumentationTitle.
        /// </summary>
        internal static string DuplicateParameterDocumentationTitle {
            get {
                return ResourceManager.GetString("DuplicateParameterDocumentationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateParameterDocumentationMessage.
        /// </summary>
        internal static string DuplicateParameterDocumentationMessage {
            get {
                return ResourceManager.GetString("DuplicateParameterDocumentationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateParameterDocumentationDescription.
        /// </summary>
        internal static string DuplicateParameterDocumentationDescription {
            get {
                return ResourceManager.GetString("DuplicateParameterDocumentationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeParameterOrderMismatchTitle.
        /// </summary>
        internal static string TypeParameterOrderMismatchTitle {
            get {
                return ResourceManager.GetString("TypeParameterOrderMismatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeParameterOrderMismatchMessage.
        /// </summary>
        internal static string TypeParameterOrderMismatchMessage {
            get {
                return ResourceManager.GetString("TypeParameterOrderMismatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeParameterOrderMismatchDescription.
        /// </summary>
        internal static string TypeParameterOrderMismatchDescription {
            get {
                return ResourceManager.GetString("TypeParameterOrderMismatchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateTypeParameterDocumentationTitle.
        /// </summary>
        internal static string DuplicateTypeParameterDocumentationTitle {
            get {
                return ResourceManager.GetString("DuplicateTypeParameterDocumentationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateTypeParameterDocumentationMessage.
        /// </summary>
        internal static string DuplicateTypeParameterDocumentationMessage {
            get {
                return ResourceManager.GetString("DuplicateTypeParameterDocumentationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateTypeParameterDocumentationDescription.
        /// </summary>
        internal static string DuplicateTypeParameterDocumentationDescription {
            get {
                return ResourceManager.GetString("DuplicateTypeParameterDocumentationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissingExceptionDocumentationTitle.
        /// </summary>
        internal static string MissingExceptionDocumentationTitle {
            get {
                return ResourceManager.GetString("MissingExceptionDocumentationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissingExceptionDocumentationMessage.
        /// </summary>
        internal static string MissingExceptionDocumentationMessage {
            get {
                return ResourceManager.GetString("MissingExceptionDocumentationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissingExceptionDocumentationDescription.
        /// </summary>
        internal static string MissingExceptionDocumentationDescription {
            get {
                return ResourceManager.GetString("MissingExceptionDocumentationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StrayReturnValueDocumentationTitle.
        /// </summary>
        internal static string StrayReturnValueDocumentationTitle {
            get {
                return ResourceManager.GetString("StrayReturnValueDocumentationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StrayReturnValueDocumentationMessage.
        /// </summary>
        internal static string StrayReturnValueDocumentationMessage {
            get {
                return ResourceManager.GetString("StrayReturnValueDocumentationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StrayReturnValueDocumentationDescription.
        /// </summary>
        internal static string StrayReturnValueDocumentationDescription {
            get {
                return ResourceManager.GetString("StrayReturnValueDocumentationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissingValueDocumentationTitle.
        /// </summary>
        internal static string MissingValueDocumentationTitle {
            get {
                return ResourceManager.GetString("MissingValueDocumentationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissingValueDocumentationMessage.
        /// </summary>
        internal static string MissingValueDocumentationMessage {
            get {
                return ResourceManager.GetString("MissingValueDocumentationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissingValueDocumentationDescription.
        /// </summary>
        internal static string MissingValueDocumentationDescription {
            get {
                return ResourceManager.GetString("MissingValueDocumentationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StrayValueDocumentationTitle.
        /// </summary>
        internal static string StrayValueDocumentationTitle {
            get {
                return ResourceManager.GetString("StrayValueDocumentationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StrayValueDocumentationMessage.
        /// </summary>
        internal static string StrayValueDocumentationMessage {
            get {
                return ResourceManager.GetString("StrayValueDocumentationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StrayValueDocumentationDescription.
        /// </summary>
        internal static string StrayValueDocumentationDescription {
            get {
                return ResourceManager.GetString("StrayValueDocumentationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LowQualityDocumentationTitle.
        /// </summary>
        internal static string LowQualityDocumentationTitle {
            get {
                return ResourceManager.GetString("LowQualityDocumentationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LowQualityDocumentationMessage.
        /// </summary>
        internal static string LowQualityDocumentationMessage {
            get {
                return ResourceManager.GetString("LowQualityDocumentationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LowQualityDocumentationDescription.
        /// </summary>
        internal static string LowQualityDocumentationDescription {
            get {
                return ResourceManager.GetString("LowQualityDocumentationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidExceptionTypeTitle.
        /// </summary>
        internal static string InvalidExceptionTypeTitle {
            get {
                return ResourceManager.GetString("InvalidExceptionTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidExceptionTypeMessage.
        /// </summary>
        internal static string InvalidExceptionTypeMessage {
            get {
                return ResourceManager.GetString("InvalidExceptionTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidExceptionTypeDescription.
        /// </summary>
        internal static string InvalidExceptionTypeDescription {
            get {
                return ResourceManager.GetString("InvalidExceptionTypeDescription", resourceCulture);
            }
        }
    }
}
